### ISSUE TITLE
Exception: UnexpectedValueException

### ISSUE THREAD

**Issue by KennFatt** [KennFatt/UnPhar#1]
```
PHP Fatal error:  Uncaught UnexpectedValueException: in phar "C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\phars\DevTools.phar", manifest claims to have zero entries.  Phars must have at least 1 entry in C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php:94
Stack trace:
#0 C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php(94): Phar->__construct('C:\\Users\\KENNAN...', 0)
#1 C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php(56): UnPhar->processExecute()
#2 C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php(20): UnPhar->init()
#3 C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php(171): UnPhar->__construct()
#4 {main}
  thrown in C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php on line 94

Fatal error: Uncaught UnexpectedValueException: in phar "C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\phars\DevTools.phar", manifest claims to have zero entries.  Phars must have at least 1 entry in C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php:94
Stack trace:
#0 C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php(94): Phar->__construct('C:\\Users\\KENNAN...', 0)
#1 C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php(56): UnPhar->processExecute()
#2 C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php(20): UnPhar->init()
#3 C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php(171): UnPhar->__construct()
#4 {main}
  thrown in C:\Users\KENNAN\Desktop\git\MyProject\UnPhar\src\unphar.php on line 94
```

Hypothesis :
Try to declare Phar with an invalid phar file.

Solution:
Check each phar by recursive-ing them.

**Comment by KennFatt** [comment]
This should be fixed in 62b44755e84826611f3b422e2c5c0c13cc070f68
